### ISSUE TITLE
License for the levenshtein DFA code?

### ISSUE THREAD

**Issue by adamfeuer** [julesjacobs/levenshtein#1]
@julesjacobs Hi, thanks for the great levenshtein DFA example! I'm working on a pattern matching project, and I'd like to use this code - but didn't see a license file. What is the license for it? Would you be willing to commit a LICENSE file to the project?

If you're willing to use an Open Source license, I'm happy to contribute my changes back to you.

cheers
adam

Seattle, WA

**Comment by julesjacobs** [comment]
Hi Adam,

I've added a license (MIT). Good luck with the code. It does need a lot of changes to be usable in real life. Let me know if you have any questions.

Jules

**Comment by adamfeuer** [comment]
Thanks Jules!
